org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=26.1.1
loader_version=0.19.3
fabric_version=0.155.2+26.1.2
fabric_command_api_version=3.0.5+e2bdee784c
fabric_key_mapping_api_version=2.0.4+e2bdee784c
fabric_lifecycle_events_api_version=4.1.1+df84eb3d4c

mod_version=0.0.1-alpha
maven_group=com.modresourcemanager
archives_base_name=mrm-fabric
